### ISSUE TITLE
system disk and tmp directory

### ISSUE THREAD

**Issue by antoine4ucsd** [yyoshiaki/VIRTUS2#41]
Hello
great work with this tool. I made it work for several samples but having space/tmp dir problems with a larger samples
I tried to adapt according to your tip my code as follow (singularity mode since docker not available on my server)
```
cwltool   --tmp-outdir-prefix=/mypath/_virtus/tmp_cwl2/ \
               --tmpdir-prefix=/mypath/_virtus/tmp_cwl2/  \
               --rm-tmpdir \
               --singularity  \
                ./VIRTUS.PE.cwl  VIRTUS.PE.localref.job2.yaml

```
and the yaml file is
```
fastq1:
  class: File
  path: >-
    /mypath/_virtus/VIRTUS2/wrapper/JFXLNRLG1_SPL_1.fastq.gz
fastq2:
  class: File
  path: >-
    /mypath/_virtus/VIRTUS2/wrapper/JFXLNRLG1_SPL_2.fastq.gz
genomeDir_human:
  class: Directory
  path: /mypath/_virtus/STAR_index_human_localref
genomeDir_virus:
  class: Directory
  path: /mypath/_virtus/STAR_index_virus_localref
nthreads: 40
outFileNamePrefix_human: human
filename_output: virtus2.filename.localref.output.tsv

```
but I still get these subfolder being created , each of them containing fastq (up to 300Go each ) and the former subdir are NOT removed.
I thought the  --rm-tmpdir  would work?

THANK YOU!
 
![image](https://github.com/yyoshiaki/VIRTUS2/assets/18502631/980023c0-30f4-42bf-a925-1b724b749e9a)
